site_name: Sidra Dashboard Documentation
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal
      accent: purple 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - offline
#   - social

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: 
#     - icon: fontawesome/brands/twitter
#       link: 
#     - icon: fontawesome/brands/linkedin
#       link: 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://www.linkedin.com/in/deep-chandra/"  target="_blank" rel="noopener">Deep Chandra</a>